[package]
name = "bitcoin_rust_seeder"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"